spring:
  application:
    name: api-gateway  
  config:
    import:
      - "optional:configserver:http://localhost:8088"
    
  cloud:
    gateway:
      discovery:
        locator:
         enabled: true
      routes:
       -
         id: department-service
         uri: lb://department-service
         predicates: Path=/department/**
       -
         id: employee-service
         uri: lb://employee-service
         predicates: Path=/employee/**
    
server:
  port: 8060
  
management:
  endpoints:
    web:
      exposure:
        include:  "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${vcap:application.uris[0]:localhost}
    prefer-ip-address: true  
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    


