server:
  port: 8082
spring:
  application:
    name: department-service
  config:
    import: 
       - "optional:configserver:http://localhost:8088"

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:8761/eureka/

      